# -*- coding: utf-8 -*-
"""reto163036.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1os7GGluAUcecFaizKwdJ-kwdzOKAi9Mh
"""

import pandas as pd
from pyspark.sql import SparkSession
from pyspark.sql import functions as F
from pyspark.sql.types import StringType

spark = SparkSession.builder.master("local[*]").getOrCreate()
spark

from google.colab import files
uploaded = files.upload()

df = spark.read.csv('pokemon.csv', header=True)
df.show(5)

def ejercicio():
  result=df.filter(~F.col('Name').contains("Mega"))\
       .filter(F.col("Legendary") == False)\
       .withColumn("2*Speed",F.col("Speed")*2)\
       .filter(F.col("2*Speed")>100)\
       .groupBy("Generation").count()\
       .withColumnRenamed("count", "Conteo")\
       .orderBy("Conteo")\
       .withColumn("Conteo",F.col("Conteo").cast(StringType()))\
       .toPandas()
  return result

a = ejercicio()
a

